# Generated by Django 3.0.6 on 2020-06-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updates',
            new_name='updated',
        ),
    ]
