# Generated by Django 3.0.6 on 2020-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='created'),
        ),
    ]
